# 第3回レポート課題


提出物：

- report03.ipynb（このノートブック）
  - ノートブックに直接コードを書いて実行できる
  - コードを実行した結果の状態で保存して提出すること
- レポート
  - 形式：A4縦，PDFファイル1つ（複数ファイルやwordファイルは受け付けない）
  - 1ページ目冒頭に，氏名・学生番号・所属学科/分野/コース・授業名・課題名・出題授業日を明記すること
  - 各課題（「課題3-01」「課題3-02」など）を区別できるようにすること
  - 含める内容
    - コードの抜粋とその説明
    - 実行結果（テキスト出力，プロット等）とその説明
    - 各課題で指定された内容とその説明
  - レポート作成上の注意事項:
    - **レポートにはできるだけ丁寧な説明を含めること**



手計算課題用スライドで空欄にしてあった後退代入の答えを必要に応じて参考にすること．

以下はnumpyで連立方程式を解くコードである．
今回はアルゴリズムの理解が目的なので，課題にはnumpyの`np.linalg.solve`を使わないこと．
（ただし，計算結果の検証用に利用するのは構わない．これを使って，自分のコードの計算結果が正しいかどうかを確認すること）

In [2]:
import numpy as np

A = np.array([
    [1, 2, 3, 4],
    [2, 5, 4, 3],
    [3, 4, 6, 5],
    [6, 5, 4, 7]]).astype(float)

b = np.array([30, 36, 49, 56]).astype(float)

print("===")
print("check the correct solusion x: ", np.linalg.solve(A, b))  # numpyの連立方程式を解く関数
print("===")


===
check the correct solusion x:  [1. 2. 3. 4.]
===


注意事項：
- 数式による説明は，変数の添字が1から$n$である場合が多い．しかし実装上は，配列のインデックスは`0`から`n-1`までである．
数式を実装する際には，数式とコードのインデックスの違いに気をつけること．
- 添字の間違いでエラーになったり正しい解が計算できない場合が多い．
これを避けるよい方法は，まず数式の時点で0から$n-1$までの添字を使って数式を導出しておくこと，
iやjなどのループ変数をループの中で表示して，想定した値になっているかどうかを常に把握することである．

## 課題3-01：前進代入


以下の`forward_substitute`関数に前進代入のプログラムを作成せよ．ただし，入力引数が下三角行列であることは仮定してよいとする．

プログラムを説明し，実行せよ．実行する例として，

- 手計算で実施した小課題(1)-1と，
- 入力となる下三角行列を自分で適当に定義したもの

の2つを示すこと．

自分で定義するものは変数を3つ以上とする．また，解が存在しなかったり一意に定まらない連立方程式を作ってしまうとうまくいかない可能性があるので注意すること．

- レポートに含めること: 実行例

In [4]:
# ヒント：昇順のループにはrangeを以下のように使う．rangeの第1引数は開始値，第2引数は終了値＋1

N = 5
for i in range(N):  # i = 0, 1, ..., N-1
    print("A: [0 ... N-1]", i)

print()

for i in range(0, N):  # i = 0, 1, ..., N-1
    print("B: [0 ... N-1]", i)

print()

for i in range(1, N + 1):  # i = 1, 2, ..., N
    print("C: [1 ... N]", i)

A: [0 ... N-1] 0
A: [0 ... N-1] 1
A: [0 ... N-1] 2
A: [0 ... N-1] 3
A: [0 ... N-1] 4

B: [0 ... N-1] 0
B: [0 ... N-1] 1
B: [0 ... N-1] 2
B: [0 ... N-1] 3
B: [0 ... N-1] 4

C: [1 ... N] 1
C: [1 ... N] 2
C: [1 ... N] 3
C: [1 ... N] 4
C: [1 ... N] 5


In [2]:
def forward_substitute(A, b):

    n = len(b)
    x = np.zeros(n)

    #
    #  コードを作成して挿入
    #

    for i in range(n):  # i = 0, 1, ..., n-1

        for j in range(i):  # j = 0, 1, ..., i-1

            print("i={}, j={}".format(i, j))

            x = 0  # これはダミーです

        x = 0  # これはダミーです

    return x


# A = np.array([
#     [8, 0, 0, 0],
#     [2, 3, 0, 0],
#     [6, 5, 4, 0],
#     [7, 8, 9, 8]
# ]).astype(float)
# b = np.array([8, 8, 12, -2]).astype(float)

A = np.array([
    [4, 0, 0, 0],
    [2, 3, 0, 0],
    [-2, 6, 1, 0],
    [2, 1, 3, 4]
]).astype(float)
b = np.array([8, 7, -12, 3]).astype(float)

print("===")
print("check the correct solusion x: ", np.linalg.solve(A, b))
print("===")


print("Solve linear equation A x = b with a lower triangular matrix A")
print("Coefficient matrix A:")
print(A)
print("Right-hand-side b:")
print(b)

print("Solution x:")
print(forward_substitute(A, b))

Solve linear equation A x = b with a lower triangular matrix A
Coefficient matrix A:
[[ 4  0  0  0]
 [ 2  3  0  0]
 [-2  6  1  0]
 [ 2  1  3  4]]
Right-hand-side b:
[  8   7 -12   3]
Solution x:
0


# 課題3-02：後退代入


以下の`backward_substitute`関数に後退代入のプログラムを作成せよ．

ただし，入力引数が上三角行列であることは仮定してよいとする．

課題3-01と同様に，

- 手計算で実施した小課題(1)-2と，
- 入力となる下三角行列を自分で適当に定義したもの

の２つの実行例を示すこと．


- レポートに含めること: 実行例

In [5]:
# ヒント：降順のループにはrangeを以下のように使う
# rangeの第1引数は開始値，第2引数は終了値-1，第3引数は増減値（-1ずつ変更する）

N = 5
for i in range(N - 1, -1, -1):  # i = N-1, N-2, ..., 1, 0
    print("A: [N-1 ... 0]", i)

print()

for i in range(N, 0, -1):  # i = N, N-2, ..., 1
    print("B: [N ... 1]", i)

A: [N-1 ... 0] 4
A: [N-1 ... 0] 3
A: [N-1 ... 0] 2
A: [N-1 ... 0] 1
A: [N-1 ... 0] 0

B: [N ... 1] 5
B: [N ... 1] 4
B: [N ... 1] 3
B: [N ... 1] 2
B: [N ... 1] 1


In [4]:
def backward_substitute(A, b):

    n = len(b)
    x = np.zeros(n)

    #
    #  コードを作成して挿入
    #

    # for i = n-1, n-2, ..., 1, 0

        # for j = i+1, i+2, ..., n-1

        #     x = 0  # これはダミーです

        # x = 0  # これはダミーです

    return x


A = np.array([
    [1., 2., 4., 3.],
    [0., 3., 2., 1.],
    [0., 0., 4., 3.],
    [0., 0., 0., 1.],
])
b = np.array([1., 2., 2., -2.])
print("===")
print("check the correct solusion x: ", np.linalg.solve(A, b))
print("===")


print("Solve linear equation A x = b with an upper triangular matrix A")
print("Coefficient matrix A:")
print(A)
print("Right-hand-side b:")
print(b)

print("Solution x:")
print(backward_substitute(A, b))

Solve linear equation A x = b with an upper triangular matrix A
Coefficient matrix A:
[[1. 2. 4. 3.]
 [0. 3. 2. 1.]
 [0. 0. 4. 3.]
 [0. 0. 0. 1.]]
Right-hand-side b:
[ 1.  2.  2. -2.]
Solution x:
0


## 課題3-03：ガウス消去法

以下にガウス消去法によって連立方程式$\boldsymbol{A} \boldsymbol{x} = \boldsymbol{b}$を解く関数`gaussian_elimination`を作成せよ．
課題3-02で作成した後退代入の関数を利用すること．

- 以下のコードに含まれているものと
- 計算小課題(3)の二つの連立方程式

で実行例を示せ．


- レポートに含めること: 実行例

In [7]:
def gaussian_elimination(A0, b0):

    # 行列の基本変形を適用する行列Aとベクトルbを用意

    b = b0
    A = A0

    n = len(b)
    x = np.zeros(n)

    # for i = ?, ..., ?
    #     for j = ?, ..., ?

            # r = ?

            # 
            # Aのi行目をr倍してj行目から引き算する操作を作成
            # 


        # bのi番目をr倍してj番目から引き算する操作を作成



    # Aが上三角になったことを確認


    # 
    # 後退代入を実行
    # 




    return x




A = np.array([
    [5, 5, -4, 3, -6],
    [2, -8, -6, 1, -1],
    [7, -2, 6, 2, 2],
    [-2, 1, -2, 9, 4],
    [-4, -3, 5, 3, -7],
]).astype(float)
b = np.array([3, 7, 8, -1, 2]).astype(float)

print("===")
print("check the correct solusion x: ", np.linalg.solve(A, b))
print("===")

print("Solve linear equation A x = b with a full matrix A")
print("Coefficient matrix A:")
print(A)
print("Right-hand-side b:")
print(b)

print("Solution x:")
print(gaussian_elimination(A, b))


Solve linear equation A x = b with a full matrix A
Coefficient matrix A:
[[ 5.  5. -4.  3. -6.]
 [ 2. -8. -6.  1. -1.]
 [ 7. -2.  6.  2.  2.]
 [-2.  1. -2.  9.  4.]
 [-4. -3.  5.  3. -7.]]
Right-hand-side b:
[ 3.  7.  8. -1.  2.]
Solution x:
[0. 0. 0. 0. 0.]


# 課題3-04（選択課題）：ガウス消去法のピボット選択



この問題は選択であり，必須ではない．

講義資料補足1を参考にガウス消去法にピボット選択操作も含めたコードを作成せよ．

ピボットの絶対値が$10^{-10}$以下ならば解が存在しないとして終了するようにせよ．


- レポートに含めること: 以下の方程式を解いた実行例

$$
\begin{align*}
 7 x_1         +   x_3 + 2 x_4 + 4 x_5 &= 8 \\
 3 x_2         + 5 x_3 + 7 x_4 + 2 x_5 &= 0 \\
   x_1 + 5 x_2 + 8 x_3 +   x_4         &= 2 \\
 2 x_1 + 7 x_2 +   x_3 +   x_4 + 9 x_5 &= 3 \\
 4 x_1 + 2 x_2         + 9 x_4 + 4 x_5 &= 3
\end{align*}
$$

In [4]:
A = np.array([
    [7, 0, 0, 2, 4],
    [3, 0, 5, 7, 2],
    [0, 5, 8, 0, 0],
    [2, 7, 0, 0, 9],
    [4, 2, 0, 9, 4],
], dtype=float)

b = np.array([8, 0, 2, 3, 3], dtype=float)

print("===")
print("check the correct solusion x: ", np.linalg.solve(A, b))
print("===")

solve in main [ 1.63744202  0.90015968 -0.3125998  -0.26971333 -0.73066687]


In [ ]:
def gaussian_elimination_with_pivot(A0, b0):

    # 行列の基本変形を適用する行列Aとベクトルbを用意

    b = b0
    A = A0

    n = len(b)
    x = np.zeros(n)

    # for i in range(n):
    #  for j in range(????, n):

        # 
        # i行目をr倍してj行目から引き算する操作を作成
        # 



    # 
    # 後退代入を実行
    # 




    return x


In [13]:
print("Solve linear equation A x = b with a full matrix A")
print("Coefficient matrix A:")
print(A)
print("Right-hand-side b:")
print(b)


# ピボットなしの計算結果は正しくない
x_solution, A, b = gaussian_elimination(A, b)

print("Solution x:")
print(x_solution)
print("Coefficient matrix A:")
print(A)
print("Right-hand-side b:")
print(b)


# ピボットありの計算結果は正しいはず
x_solution, A, b = gaussian_elimination_with_pivot(A, b)

print("Solution x:")
print(x_solution)
print("Coefficient matrix A:")
print(A)
print("Right-hand-side b:")
print(b)




Solve linear equation A x = b with a full matrix A
Coefficient matrix A:
[[7. 0. 0. 2. 4.]
 [3. 0. 5. 7. 2.]
 [0. 5. 8. 0. 0.]
 [2. 7. 0. 0. 9.]
 [4. 2. 0. 9. 4.]]
Right-hand-side b:
[8. 0. 2. 3. 3.]


NameError: name 'gaussian_elimination' is not defined