<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Pythonとnotebookの使い方" data-toc-modified-id="Pythonとnotebookの使い方-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Pythonとnotebookの使い方</a></span><ul class="toc-item"><li><span><a href="#Python" data-toc-modified-id="Python-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Python</a></span></li><li><span><a href="#IPythonとは" data-toc-modified-id="IPythonとは-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>IPythonとは</a></span></li><li><span><a href="#Jupyter-Notebookとは" data-toc-modified-id="Jupyter-Notebookとは-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Jupyter Notebookとは</a></span></li><li><span><a href="#Google-Colaboratoryとは" data-toc-modified-id="Google-Colaboratoryとは-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Google Colaboratoryとは</a></span><ul class="toc-item"><li><span><a href="#Task" data-toc-modified-id="Task-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Task</a></span></li></ul></li><li><span><a href="#notebookの注意点" data-toc-modified-id="notebookの注意点-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>notebookの注意点</a></span><ul class="toc-item"><li><span><a href="#値の変更" data-toc-modified-id="値の変更-1.5.1"><span class="toc-item-num">1.5.1&nbsp;&nbsp;</span>値の変更</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.5.2"><span class="toc-item-num">1.5.2&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#notebookカーネルの再起動" data-toc-modified-id="notebookカーネルの再起動-1.5.3"><span class="toc-item-num">1.5.3&nbsp;&nbsp;</span>notebookカーネルの再起動</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.5.4"><span class="toc-item-num">1.5.4&nbsp;&nbsp;</span>Task</a></span></li></ul></li><li><span><a href="#Pythonの簡単な使い方" data-toc-modified-id="Pythonの簡単な使い方-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Pythonの簡単な使い方</a></span><ul class="toc-item"><li><span><a href="#型，代入，計算，表示" data-toc-modified-id="型，代入，計算，表示-1.6.1"><span class="toc-item-num">1.6.1&nbsp;&nbsp;</span>型，代入，計算，表示</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.6.2"><span class="toc-item-num">1.6.2&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.6.3"><span class="toc-item-num">1.6.3&nbsp;&nbsp;</span>Task</a></span></li></ul></li><li><span><a href="#リスト" data-toc-modified-id="リスト-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>リスト</a></span><ul class="toc-item"><li><span><a href="#Task" data-toc-modified-id="Task-1.7.1"><span class="toc-item-num">1.7.1&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.7.2"><span class="toc-item-num">1.7.2&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.7.3"><span class="toc-item-num">1.7.3&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#2次元配列：リストのリスト" data-toc-modified-id="2次元配列：リストのリスト-1.7.4"><span class="toc-item-num">1.7.4&nbsp;&nbsp;</span>2次元配列：リストのリスト</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.7.5"><span class="toc-item-num">1.7.5&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.7.6"><span class="toc-item-num">1.7.6&nbsp;&nbsp;</span>Task</a></span></li></ul></li><li><span><a href="#array" data-toc-modified-id="array-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>array</a></span><ul class="toc-item"><li><span><a href="#Task" data-toc-modified-id="Task-1.8.1"><span class="toc-item-num">1.8.1&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.8.2"><span class="toc-item-num">1.8.2&nbsp;&nbsp;</span>Task</a></span></li></ul></li><li><span><a href="#便利な関数" data-toc-modified-id="便利な関数-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>便利な関数</a></span><ul class="toc-item"><li><span><a href="#Task" data-toc-modified-id="Task-1.9.1"><span class="toc-item-num">1.9.1&nbsp;&nbsp;</span>Task</a></span></li></ul></li><li><span><a href="#arrayの型変換" data-toc-modified-id="arrayの型変換-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>arrayの型変換</a></span><ul class="toc-item"><li><span><a href="#Task" data-toc-modified-id="Task-1.10.1"><span class="toc-item-num">1.10.1&nbsp;&nbsp;</span>Task</a></span></li></ul></li><li><span><a href="#制御文" data-toc-modified-id="制御文-1.11"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>制御文</a></span><ul class="toc-item"><li><span><a href="#if" data-toc-modified-id="if-1.11.1"><span class="toc-item-num">1.11.1&nbsp;&nbsp;</span>if</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.11.2"><span class="toc-item-num">1.11.2&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#for" data-toc-modified-id="for-1.11.3"><span class="toc-item-num">1.11.3&nbsp;&nbsp;</span>for</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.11.4"><span class="toc-item-num">1.11.4&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.11.5"><span class="toc-item-num">1.11.5&nbsp;&nbsp;</span>Task</a></span></li></ul></li><li><span><a href="#論理式" data-toc-modified-id="論理式-1.12"><span class="toc-item-num">1.12&nbsp;&nbsp;</span>論理式</a></span><ul class="toc-item"><li><span><a href="#Task" data-toc-modified-id="Task-1.12.1"><span class="toc-item-num">1.12.1&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.12.2"><span class="toc-item-num">1.12.2&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#改行しないprint" data-toc-modified-id="改行しないprint-1.12.3"><span class="toc-item-num">1.12.3&nbsp;&nbsp;</span>改行しないprint</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.12.4"><span class="toc-item-num">1.12.4&nbsp;&nbsp;</span>Task</a></span></li></ul></li><li><span><a href="#インデキシング，スライシング" data-toc-modified-id="インデキシング，スライシング-1.13"><span class="toc-item-num">1.13&nbsp;&nbsp;</span>インデキシング，スライシング</a></span><ul class="toc-item"><li><span><a href="#Task" data-toc-modified-id="Task-1.13.1"><span class="toc-item-num">1.13.1&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#範囲指定" data-toc-modified-id="範囲指定-1.13.2"><span class="toc-item-num">1.13.2&nbsp;&nbsp;</span>範囲指定</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.13.3"><span class="toc-item-num">1.13.3&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.13.4"><span class="toc-item-num">1.13.4&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.13.5"><span class="toc-item-num">1.13.5&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.13.6"><span class="toc-item-num">1.13.6&nbsp;&nbsp;</span>Task</a></span></li></ul></li><li><span><a href="#arrayの要素毎の処理" data-toc-modified-id="arrayの要素毎の処理-1.14"><span class="toc-item-num">1.14&nbsp;&nbsp;</span>arrayの要素毎の処理</a></span><ul class="toc-item"><li><span><a href="#Task" data-toc-modified-id="Task-1.14.1"><span class="toc-item-num">1.14.1&nbsp;&nbsp;</span>Task</a></span></li><li><span><a href="#行列に対する等号不等号" data-toc-modified-id="行列に対する等号不等号-1.14.2"><span class="toc-item-num">1.14.2&nbsp;&nbsp;</span>行列に対する等号不等号</a></span></li><li><span><a href="#Task" data-toc-modified-id="Task-1.14.3"><span class="toc-item-num">1.14.3&nbsp;&nbsp;</span>Task</a></span></li></ul></li><li><span><a href="#便利な関数" data-toc-modified-id="便利な関数-1.15"><span class="toc-item-num">1.15&nbsp;&nbsp;</span>便利な関数</a></span><ul class="toc-item"><li><span><a href="#Task" data-toc-modified-id="Task-1.15.1"><span class="toc-item-num">1.15.1&nbsp;&nbsp;</span>Task</a></span></li></ul></li></ul></li></ul></div>

# Pythonとnotebookの使い方

## Python

[Python](https://www.python.jp)とは，科学技術計算から大規模webサービスまで様々な分野で利用されているスクリプト言語です．


## IPythonとは

[IPython](https://ipython.org)は，Pythonのインタラクティブな実行環境です．

## Jupyter Notebookとは

[Jupyter notebook](http://jupyter.org)とは，IPythonなどの言語をブラウザベースで実行することができる，インタラクティブな実行環境です．
計算手順と計算結果を（まさにこのドキュメントのように）そのまま残すことができる，便利なツールです．
基本的にはローカルに実行環境を構築（インストール）する必要があります．

## Google Colaboratoryとは

[Google Colaboratory](http://colab.research.google.com/)とは，Google上の仮想マシンでnotebookをブラウザベースで実行することができる，インタラクティブな実行環境です．ローカルに実行環境がなくてもクラウド上で実行が可能です．


では，この下の灰色の部分（セルと呼びます）にカーソルを移動して，そこでCtrl+Enterを押してください．これでそのセルのコードが実行できます．
今後も，コードを実行するには「Ctrl+Enter」ですので，覚えておいてください．

In [1]:
1 + 1

2

正しい答えが表示されましたか？　OK！　次に行きましょう． 
- この下のセルに移動して「Ctrl+Enter」でコードを実行してください
- もしくは，このセルで「Sift+Enter」を押してください．すると，次のセルに移動します．もう一度「Sift+Enter」を押すと，次のセルが実行できます．
（今後はいちいち書きませんよ）．

In [2]:
# ここはコメントです．

f = 150      # 変数fをつかう
g = 200 + f  # 変数gを使う
print(f)  # 変数fを表示
print(g)  # 変数gを表示

150
350


jupyter notebookではセルが計算の単位です．
- セルとセルの間に，新しいセルを追加したい場合には，上のメニューから「Insert Cell Above/Below」を選んでください．

### Task

このすぐ下に新しいセルを追加して，そのセルに`8*34`を入力し，実行して答えを表示させてください．

In [3]:
8 * 34

272

## notebookの注意点


### 値の変更
上の方のセルで使用した変数`f`と`g`は，ここでも使えます．

In [6]:
print(f, g)

100 80


値もそのまま残っていますね．しかし，以下のコードを実行すると，値が書き換わります．

In [5]:
f = 100
g = 80

もう一度，fとgの値を表示している上のセルに戻って，実行し直してみてください．表示される値が変わっているはずです．
このように，いつ変数が宣言されていつ値が書き換わるのかが，普通のプログラミングとは少し違うので，注意してください．

### Task

値が変わっていることを確認してください．

### notebookカーネルの再起動

上記の変数fとgは，notebookのカーネル（裏で動いている実体）が終了したり再起動したりすると，使えなくなります．

### Task

一番上に表示されているメニューの「Kernel」から「Restart（再起動）」を選んでください．
これまで実行した結果（宣言した変数や保存されている値）が，すべて消えてなくなります！
再起動してから，以下のコードを実行すると，宣言されていない変数f,gを参照した，というエラーが出るはずです．それを確認してください．

（Colabの場合には「ランタイム」から「ランタイムを再起動」を選択）

In [1]:
print(f, g)

NameError: ignored

エラーの内容
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-1fc60b275fa3> in <module>()
----> 1 print(f, g)

NameError: name 'f' is not defined
```



IPython notebookを終了してまた起動しても，同じことが起こります．
Notebookは，インタラクティブに変数の値を書き換えることができる便利なツールですが，
再起動のタイミングや，「一旦保存して，明日また起動しよう」ということを
した時に，予期しないエラーに遭遇するかもしれませんので，注意してください．

## Pythonの簡単な使い方

###  型，代入，計算，表示

セルでは，最後の行で評価された値が表示されます．

In [2]:
a = 10
20

20

In [3]:
a

10

In [4]:
print(a)

10


「a」を値を表示したければセルの最後で`a`とするだけでもよいです．しかし複数の値を表示したい場合には`print`を使います．

また，式評価とprintの出力が違う場合もあるので注意してください．

In [5]:
print(10)
print(20)
print(a)

10
20
10


Pythonでは，明示的に型を指定する必要はありません．
- 代入する場合には`=`を使います
- 変数の型を知りたい場合には`type()`を使います
- 表示するには`print()`を使います

In [6]:
a = 10
print(a, type(a))

10 <class 'int'>


In [7]:
a = 10.2
print(a, type(a))

10.2 <class 'float'>


In [8]:
a = "this is a text"
print(a, type(a))

this is a text <class 'str'>


In [9]:
print(5 / 2, "is float")  # 除算
print(5 // 2, "is int")  # 商
print(5 % 2, "is int")  # あまり

2.5 is float
2 is int
1 is int


In [10]:
a = 10
print(a, type(a))

a = float(a)  # floatへ変換するにはfloat()を使います
print(a, type(a))

a = int(a)  # intへ変換するにはint()を使います
print(a, type(a))

a = str(a)  # 文字列へ変換するにはstr()を使います
print('a is ' + a, ', and its type is ' + str(type(a)))

10 <class 'int'>
10.0 <class 'float'>
10 <class 'int'>
a is 10 , and its type is <class 'str'>


In [11]:
str1 = "this is"
str2 = 'a text'

str3 = str1 + " " + str2  # 文字列をつなげるときには + を使う
print(str3)

this is a text


In [1]:
num1 = 234
num2 = 22

str3 = "first number is " + str(num1) + " and second is " + str(num2)  # 数値は文字列に変換してからつなげる
print(str3)

first number is 234 and second is 22
first number is 234 and second is 22


In [15]:
# pythonでコードを改行して続けるにはバックスラッシュを使います
str3 = "first number is " \
    + str(num1) \
    + " and second is " \
    + str(num2)
print(str3)

value_sum = 1 + 2 \
    + 4 - 5 * 6 \
    / 4
print(value_sum)

# カッコの中ではバックスラッシュなしで改行できます
print("sting:", str3, "\n",
      "value_sum:", value_sum, "\n",
      "value_sum:", 1 + 2
      + 4 - 5 * 6
      / 4
      )

first number is 234 and second is 22
-0.5
sting: first number is 234 and second is 22 
 value_sum: -0.5 
 value_sum: -0.5


### Task

変数a, b, cにそれぞれ10, 20.0, 30を代入し，
合計をdに代入してその値を"sum is "の文字列の後に表示してください．

さらに，それを3で割った商と，3による除算を計算して表示してください．

ヒント：数値の変数は，文字列に変換してから，他の文字列とつなげます

### Task

以下のコードを実行するとエラーがでます．エラーをなくして正しく実行できるようにしてください．

In [13]:
b　=　10  # 全角スペースが入っている
print(b)

c ＝ 20  # 全角の＝になっている
print(c)

SyntaxError: ignored

## リスト

Pythonでもっとも重要な型がリスト（配列）です．要素を並べて`[]`でくくれば出来上がりです．

In [14]:
a = [0, 1, 2, 3, 4]  # 1次元配列
print(a)
print(type(a))

[0, 1, 2, 3, 4]
<class 'list'>


要素にアクセスするには`[]`でインデックスを指定します

In [15]:
a[3] = 100

print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

print(a)

0
1
2
100
4
[0, 1, 2, 100, 4]


### Task

10から15までの整数のリストbを作って，printで一度に表示してください．また，それぞれの要素をprintで表示してください．

### Task

リストの要素の個数は`len(リスト名)`で得られます．

`len(a)`を使って，リストaの要素の個数を表示してください．

連続する数値のリストを作成するには`range()`を使います．（ただしpython3では`range`はイテレータオブジェクトを返すので，リストに変換するために`list()`を使います）

In [16]:
list(range(10))  # 0から9まで（10未満）

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
list(range(4, 8))  # 4から7まで（8未満）

[4, 5, 6, 7]

### Task

-50から50までの整数からなるリストを作成して表示してください．

一つのリストの中に，異なる型の要素を入れることもできます（できますが，分かりにくいので使わないでください）．

In [1]:
a = [0, 1.3, "hello", 3, 1+4j]
print(a)
print(type(a))

[0, 1.3, 'hello', 3, (1+4j)]
<class 'list'>


In [3]:
print(a[0], type(a[0]))  # 整数
print(a[1], type(a[1]))  # 実数
print(a[2], type(a[2]))  # 文字列
print(a[3], type(a[3]))  # 整数
print(a[4], type(a[4]))  # 複素数

0 <class 'int'>
1.3 <class 'float'>
hello <class 'str'>
3 <class 'int'>
(1+4j) <class 'complex'>


### 2次元配列：リストのリスト

2次元配列は`[]`の中に要素としてリストを指定します．

In [20]:
a = [[0, 1, 2], [3, 4, 5, 6], [7]]
print(a)

[[0, 1, 2], [3, 4, 5, 6], [7]]


In [21]:
print(a[0])  # aの中の最初のリスト
print(a[1])  # aの中の次のリスト

[0, 1, 2]
[3, 4, 5, 6]


In [22]:
print(a[0][0])  # aの中の最初のリストa[0]の，最初の要素[0]
print(a[1][0])  # aの中の最初のリストa[1]の，最初の要素[0]

print(a[0][1])  # aの中の最初のリストa[0]の，２つ目の要素[1]
print(a[1][1])  # aの中の最初のリストa[1]の，２つ目の要素[1]

0
3
1
4


### Task
```
[0,1]
[2,3]
[4,5]
```
という2次元リストaを作成し，表示してください．また一番右下の要素だけを表示してください．

### Task

2次元リストの縦のサイズも`len`で取得できます．

リスト
`
a = [ [0, 1, 2], [3, 4, 5, 6], [7] ]
`
の要素はリストなので，要素の個数をlenで表示してください．3になるはずです．


さらにそれぞれの要素に対して，lenで個数を表示してください．
（それぞれ3, 4, 1になるはずです）



In [24]:
a = [[0, 1, 2], [3, 4, 5, 6], [7]]

## array

行列計算や画像処理で用いる2次元配列はarrayもしくはndarrayと呼ばれます．
これを使うためには，numpyというモジュールを読み込む必要があります．


In [1]:
# notebookカーネルを起動したときには，毎回この読み込みが必要になります
import numpy as np

これ以降はnpという識別子を使います．

In [2]:
a = np.array([10, 20, 30])  # リストから1次元arrayを作る
print(a)
print(type(a))  # aの型はnumpyのarray（正確にはN次元array: ndarray）

[10 20 30]
<class 'numpy.ndarray'>


np.arrayのデータの型を調べるには.dtypeを使います．

In [3]:
print(a.dtype)  # aのデータの型はint64

int64


### Task

リストと違い，arrayの要素の型はすべて同じでなければなりません．
一つでも実数値の要素があると，すべての要素が実数値になります．

以下の3つのarrayの型を，`.dtype`を使って表示して確認してください．

In [4]:
a = np.array([10, 20, 30])
print(a)

b = np.array([10, 20, 30.0])
print(b)

c = np.array([10, 20, "test"])
print(c)

[10 20 30]
[10. 20. 30.]
['10' '20' 'test']


2次元arrayも2次元リストと同様に作成できます．

In [5]:
a = np.array([[0, 1, 2], [3, 4, 5]])  # 2次元array
print(a, a.dtype)  # 型はint

[[0 1 2]
 [3 4 5]] int64


In [6]:
# 以下のように見やすく改行して与えることもできます

a = np.array([[0, 1, 2],
              [3, 4, 5]])

a = np.array(
    [[0, 1, 2],
     [3, 4, 5]])

a = np.array([
    [0, 1, 2],
    [3, 4, 5]
])

リストとは違い，arrayの要素の型は数値のみで，すべて同じになります．

In [7]:
a = np.array([[0, 1.5, 2], [3, 4, 5]])  # ひとつでも実数があると
print(a, a.dtype)  # 型はfloat

[[0.  1.5 2. ]
 [3.  4.  5. ]] float64


2次元arrayを行列とみなして，行列計算もできます．

In [9]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a = 0.1 * a  # スカラー倍
b = a.T  # 転置
print('a is \n', a)
print('b is \n', b)

a is 
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]]
b is 
 [[0.  0.3]
 [0.1 0.4]
 [0.2 0.5]]


乗算は，要素ごとの積になります．注意！

In [10]:
a * a

array([[0.  , 0.01, 0.04],
       [0.09, 0.16, 0.25]])

In [11]:
# これはエラーになります．aとbの次元が違うので

a * b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

エラーの内容
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-efe16d370064> in <module>()
----> 1 a * b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 
```

aとbの内積や，行列同士の積を計算したい場合には，`.dot()`を使います．`np.dot()`でもできます．また`@`を使うことも出来ます）．

In [38]:
a.dot(b)  # a.b

array([[0.05, 0.14],
       [0.14, 0.5 ]])

In [39]:
np.dot(a, b)  # a.b

array([[0.05, 0.14],
       [0.14, 0.5 ]])

In [40]:
a @ b

array([[0.05, 0.14],
       [0.14, 0.5 ]])

### Task

2つの行列
$
\begin{pmatrix}
1 & 0  \\
0 & 1
\end{pmatrix}
$
と
$
\begin{pmatrix}
1 & 2  \\
3 & 4
\end{pmatrix}
$
を作ります．
この2つの行列の

- 要素ごとの積
- 要素ごとの和（つまり普通の行列の和）
- 行列の積

を計算して表示してください．



## 便利な関数

numpyには便利な関数がたくさんあります．
この先に必要で重要なものをいくつか以下に示します．

まずは0から1までの実数乱数のベクトルや行列を作る関数です．

In [41]:
# サイズが10の乱数arrayを作る．値は0から1までの実数
a = np.random.rand(10)

# サイズが3x4の乱数arrayを作る．値は0から1までの実数
b = np.random.rand(3, 4)

print("a is ")
print(a)
print("b is")
print(b)

a is 
[0.490814   0.42267748 0.81441026 0.21928734 0.82341722 0.78444864
 0.36432737 0.23721344 0.21699485 0.58627822]
b is
[[0.06613794 0.52609035 0.49012967 0.28049996]
 [0.34490035 0.1503054  0.18833388 0.66317476]
 [0.79489178 0.61483038 0.02390171 0.1037082 ]]


次は整数乱数のベクトルや行列を作る関数です．randとrandintは使い方が違うので注意してください．

In [42]:
# サイズが10の乱数arrayを作る．値は0から99までの整数（100までではないので注意！）
a = np.random.randint(100, size=(10))

# サイズが3x4の乱数arrayを作る．値は0から49までの整数
b = np.random.randint(50, size=(3, 4))

print("a is ", a)
print("b is\n", b)

a is  [36  0  8 35  8 57 73 64  0 84]
b is
 [[25 32  3 25]
 [26 42  5  2]
 [17 32 12  9]]


次はゼロや1からなるベクトル・行列を作る関数です．

In [16]:
# サイズが3x8のゼロ行列を生成
a = np.zeros(shape=(3, 8))
print("a is \n", a)

# "shape="を省略することもできます
a = np.zeros((3, 8))  # np.zeros(3, 8)ではないことに注意！
print("a is \n", a)

# サイズが8のゼロベクトルを生成
b = np.zeros(8)
print("b is ", b)

a is 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
a is 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
b is  [0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
# サイズが3x8の1行列を生成
a = np.ones(shape=(3, 8))
print("a is \n", a)

# "shape="を省略することもできます
a = np.ones((3, 8))  # np.ones(3, 8)ではないことに注意！
print("a is \n", a)

# サイズが8の1ベクトルを生成
b = np.ones(8)
print("b is ", b)

a is 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
a is 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
b is  [1. 1. 1. 1. 1. 1. 1. 1.]


numpyの関数`np.arange()`は，連続する数値のndarrayを作る関数です．使い方は`range()`と同じですが，arrayが返ります．

In [45]:
a = np.arange(10)  # 0から9までのarray
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
a = np.arange(-8, 8)  # -8から7までのarray
print(a)

[-8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7]


In [47]:
a = np.arange(-13, 13, 4)  # -13から12まで4つ毎のarray
print(a)

[-13  -9  -5  -1   3   7  11]


配列の縦横サイズ（形，shape）を取得する関数はshape（またはsize）です．
shapeは縦と横をタプル（値の組）で返します．

In [18]:
a = np.array([[0, 1, 2], [3, 4, 5]])  # 2x3の行列

print(a.shape)  # array（行列）のサイズを表示

h = a.shape[0]  # 縦のサイズを左辺に代入
w = a.shape[1]  # 横のサイズを左辺に代入
print("height is ", h, "\n", "width is ", w)

h, w = a.shape  # 縦横のサイズを左辺に代入．これでもOK
print("height is ", h, "\n", "width is ", w)

print("total number of elements is ", a.size)  # size = w * h

(2, 3)
height is  2 
 width is  3
height is  2 
 width is  3
total number of elements is  6


In [49]:
a = np.arange(10)  # 0から9までのarray
print(a)
print(a.shape)  # 1次元arrayの場合，shapeは1つ目しか返ってこない
print(a.size)  # 1次元arrayのサイズ．len(a)と同じ
print(len(a))

[0 1 2 3 4 5 6 7 8 9]
(10,)
10
10


### Task

- 5x8の乱数行列
- 6x3のゼロ行列
- 要素が全て1の長さ10の1次元ベクトル

を生成して，その縦横のサイズが指定したとおりになっているかどうか，.shapeを表示して確認してください．



## arrayの型変換

ndarrayの要素はすべて同じ型です．それを変換する方法があります．

In [25]:
a = np.random.randint(50, size=(3, 4)) - 25  # -25から24までの整数乱数の3x4行列

print(a)

print(a.dtype)  # aは符号付き64ビット整数（int64）であることを確認

[[  1 -22  11 -10]
 [ -7   6 -12  -7]
 [  2   6  -6 -13]]
int64


In [26]:
b = a.astype(float)  # aをfloatに変換する．
print(b)
print(b.dtype)  # bはfloatになる．pythonではfloatは64bit浮動小数点数

[[  1. -22.  11. -10.]
 [ -7.   6. -12.  -7.]
 [  2.   6.  -6. -13.]]
float64


In [27]:
b = np.float64(a)  # aをfloatに変換する別のやり方
print(b)
print(b.dtype)  # bはfloat64

[[  1. -22.  11. -10.]
 [ -7.   6. -12.  -7.]
 [  2.   6.  -6. -13.]]
float64


In [28]:
b = np.float32(a)  # aをfloat32に変換（32bit浮動小数点数）
print(b)
print(b.dtype)  # bはfloat32

b = a.astype(np.float32)  # aをfloat32に変換
print(b)
print(b.dtype)  # bはfloat32

[[  1. -22.  11. -10.]
 [ -7.   6. -12.  -7.]
 [  2.   6.  -6. -13.]]
float32
[[  1. -22.  11. -10.]
 [ -7.   6. -12.  -7.]
 [  2.   6.  -6. -13.]]
float32


In [29]:
b = np.float16(a)  # aをfloat16に変換（16bit浮動小数点数）
print(b)
print(b.dtype)  # bはfloat32

b = a.astype(np.float16)  # aをfloat16に変換
print(b)
print(b.dtype)  # bはfloat32

[[  1. -22.  11. -10.]
 [ -7.   6. -12.  -7.]
 [  2.   6.  -6. -13.]]
float16
[[  1. -22.  11. -10.]
 [ -7.   6. -12.  -7.]
 [  2.   6.  -6. -13.]]
float16


In [30]:
c = b.astype(np.uint8)  # unsigned int 8bit （uint8，C言語でのunsigned charに相当）に変換する
print(c)
print(c.dtype)  # cは符号なし8ビット整数

[[  1 234  11 246]
 [249   6 244 249]
 [  2   6 250 243]]
uint8


In [31]:
d = b.astype(np.int32)  # signed int 32bit （int32，C言語でのsigned intに相当）に変換する
print(d)
print(d.dtype)  # dは符号つき32ビット整数

[[  1 -22  11 -10]
 [ -7   6 -12  -7]
 [  2   6  -6 -13]]
int32


In [32]:
# unsigned int 32bit （uint32，C言語でのunsigned intに相当）に変換する
e = b.astype(np.uint32)
print(e)
print(e.dtype)  # dは符号なし32ビット整数．負の数を変換する場合には，変換結果は正しくない

[[         1 4294967274         11 4294967286]
 [4294967289          6 4294967284 4294967289]
 [         2          6 4294967290 4294967283]]
uint32


In [33]:
# bool値（真偽値）は，Falseが0，Trueは0以外を意味する

a = np.array([True, False, False, True])  # boolのarray
print(a, a.dtype)

b = a.astype(int)  # boolを整数に変換
print(b)

c = np.array([[0, 0, -1], [1, 0, 8]])  # 整数のarray
print(c)

d = c.astype(bool)  # 整数をboolに変換
print(d)

[ True False False  True] bool
[1 0 0 1]
[[ 0  0 -1]
 [ 1  0  8]]
[[False False  True]
 [ True False  True]]


### Task

要素が0か1の整数である乱数行列を作成して，それをbool型の行列に変換してください．

## 制御文

Pythonの主要な制御文はifとforです．

### if

In [57]:
a = 10

if a > 5:

    # if中はかならずインデントしてください（インデントとは，左側を空白4個分空けることです）
    print("a is larger than 5")
    print("a is ", a)

else:  # elseとifのインデントは同じにしてください

    # elseも同様にインデントしてください
    print("a is smaller than 5")
    print("a is ", a)

# インデントが正しくないと，エラーになります

a is larger than 5
a is  10


In [ ]:
a = 8

if a <= 10:
    print("a is smaller than or equal to 10")
else:
    print("a is larger than 10")

if a < 10:
    print("a is smaller than 10")
elif a >= 10:
    print("a is larger than or equal to 10")
elif a == 10:
    print("a is equal to 10")
elif a != 10:
    print("a is not equal to 10")
else:
    print("a is a number")

### Task

以下のコードのエラーを修正して，エラーがなく実行できるように修正してください．

In [58]:
a = 10

if a > 5:
    print("a is larger than 5")
    print("a is ", a)
 else:
   print("a is smaller than 5")
  print("a is ", a)

IndentationError: ignored

### for
forループのループ範囲指定には，リストかarrayを使います．

In [60]:
for i in [4, 5, 6, 7]:  # forループの指定にはリストかarrayを使う

    # for中もインデントしてください
    print("i is ", i)

i is  4
i is  5
i is  6
i is  7


In [61]:
for i in range(10):  # forループでの範囲指定に使う場合にはlist(range(10))とはしない
    print("i is ", i)

i is  0
i is  1
i is  2
i is  3
i is  4
i is  5
i is  6
i is  7
i is  8
i is  9


### Task

以下のコードのループ範囲指定にnp.arangeを使って，上のforループと同じことを実現してください．

In [ ]:
for i in *******:
    print("i is ", i)

### Task

以下のコードのエラーを修正してください．

In [ ]:
for i in np.arange(1, 5):

print("i is ", i)

## 論理式

一般的な比較演算子(>, <, ==, <=, >=)や論理式(and, or, not)を使うことができます．

In [62]:
if 10 > 4:
    print("yes, it is true.")
else:
    print("this never happens.")

yes, it is true.


In [25]:
a = 10
b = 20

if a == 10:
    print("ok, a is 10.")

if a == 10 and b == 10:
    print("a == b == 10")
elif a == 10 and b == 20:
    print("a == 10, b == 20")

ok, a is 10.
a == 10, b == 20


In [26]:
a = 0
b = 10

if a <= 10 and b >= 10:
    print("a <= 10 and b >= 10")

if a < 10 or b > 12:
    print("a < 10 or b > 12")

if not a >= 10:
    print("not a >= 10")

a <= 10 and b >= 10
a < 10 or b > 12
not a >= 10


pythonでは`3 <= i < 7`のように，比較演算子を連続して使う書き方ができます．

なおC言語などこれが使えない（エラーにはならないが意味が異なる）言語もあります．（`3 <= i < 7`は左から解釈されて`(3 <= i) < 7`となり，`i`の値に応じて`True < 7`または`False < 7`と解釈されます．C言語はTrueが1，Falseが0という真偽値から整数値への暗黙の型変換が行われるため，最終的に`1 < 7`または`0 < 7`という解釈されます．この結果，変数iの値が3以上7未満，という判定はされません）

In [6]:
for i in range(10):
    if 3 <= i < 7:
        print(i, ": 3 <= i < 7")
    else:
        print(i, ": i < 3 or 7 <= i")

0 : i < 3 or 7 <= i
1 : i < 3 or 7 <= i
2 : i < 3 or 7 <= i
3 : 3 <= i < 7
4 : 3 <= i < 7
5 : 3 <= i < 7
6 : 3 <= i < 7
7 : i < 3 or 7 <= i
8 : i < 3 or 7 <= i
9 : i < 3 or 7 <= i


### Task

100以下の偶数をforループで表示してください．余りを計算する演算子は`%`です．

In [64]:
# 100以下の偶数をforループで表示してください．

### Task

forとifの組み合わせで，100以下の3と5の公倍数を表示してください．

3の公倍数かどうかは，3で割ったあまりが0かどうかで判定します．
「3の公倍数であり，かつ5の公倍数である」を表現するには，`and`を使います．

In [65]:
# forとifの組み合わせで，3と5の公倍数を表示

### 改行しないprint

forループの中のprint()で改行したくない場合には，オプションにend=""を指定します．以下の例を見てください．

In [67]:
# 二重ループ
for i in np.arange(3):
    for j in np.arange(3):
        print(i, end="")  # end指定はprintの後に表示する内容（デフォルトでは"\n"）
        print(" +", j, end="")
        print(" = ", i+j)
    print("----")

0 + 0 =  0
0 + 1 =  1
0 + 2 =  2
----
1 + 0 =  1
1 + 1 =  2
1 + 2 =  3
----
2 + 0 =  2
2 + 1 =  3
2 + 2 =  4
----


### Task

二重ループで九九の掛け算表を表示してください．

## インデキシング，スライシング

pythonでは，array（配列）の操作が重要です．よく覚えてください．

### インデキシング

インデキシングとは要素の番号を指定して値を参照することです．つまり普通の配列の要素アクセスと同じです．

In [35]:
# まずランダムな5x5行列aを作ります
a = np.random.randint(50, size=(5, 5))

In [36]:
a  # 中身を確認

array([[41, 31,  9,  7, 27],
       [35, 38, 46, 27, 34],
       [26, 29, 34, 30,  7],
       [18,  5, 14,  0, 33],
       [12, 46,  4, 32, 23]])

In [37]:
# 値を取り出すには，インデックスで指定する
print(a[0, 0], a[1, 4], a[4, 0])

41 34 12


In [38]:
# 値を代入するにも，インデックスで指定する
a[0, 0] = 100
a[1, 4] = 200
a[4, 0] = 300

In [39]:
a  # 値が変わっていることを確認

array([[100,  31,   9,   7,  27],
       [ 35,  38,  46,  27, 200],
       [ 26,  29,  34,  30,   7],
       [ 18,   5,  14,   0,  33],
       [300,  46,   4,  32,  23]])

### Task

上記の行列aのすべての対角要素を1にしてください．

### スライシングによる範囲指定

インデックスの範囲を指定して，arrayの部分をarrayとして参照するスライシングという機能があります．
インデックスの範囲を指定するときには`:`を使います．以下の例をみてください．

In [40]:
# 範囲を指定すると部分行列（部分配列）が取り出せる

a[0:2, 1:4]

# 最初の指定「0:2」上から0,1行目（2は含まない）を取り出す
# 次の指定　「1:4」左から1,2,3列目（4は含まない）を取り出す

array([[31,  9,  7],
       [38, 46, 27]])

In [41]:
# 指定した範囲にスカラーを代入できる
a[0:2, 1:4] = 33

print(a)  # 確認

[[100  33  33  33  27]
 [ 35  33  33  33 200]
 [ 26  29  34  30   7]
 [ 18   5  14   0  33]
 [300  46   4  32  23]]


In [42]:
# 指定した範囲に行列を代入できる

a[0:2, 1:4] = np.ones(shape=(2, 3))

a  # 確認

array([[100,   1,   1,   1,  27],
       [ 35,   1,   1,   1, 200],
       [ 26,  29,  34,  30,   7],
       [ 18,   5,  14,   0,  33],
       [300,  46,   4,  32,  23]])

In [43]:
a[0:4, 1:2]  # 1列目だけ列として取り出す方法：その1

array([[ 1],
       [ 1],
       [29],
       [ 5]])

In [44]:
a[:, 1:2]  # 1列目だけ列として取り出す方法：その2．:だけならすべての範囲を意味します

array([[ 1],
       [ 1],
       [29],
       [ 5],
       [46]])

In [45]:
a[:, 1]  # 1列目だけ取り出す方法（これは行，つまり1次元配列になる）

array([ 1,  1, 29,  5, 46])

In [79]:
a[1:2, :]  # １行目だけ行として取り出す

array([[ 12,   1,   1,   1, 200]])

In [80]:
a[1, :]  # １行目だけ１次元配列として取り出す

array([ 12,   1,   1,   1, 200])

### Task

aの右下2x2の部分を0にしてください．

### Task

aの一番下の行を0にしてください．

### Task

aの一番左側の列を1にしてください．

### Task

8x12の乱数行列を生成し，左側の8x8部分行列を取り出してください．

## arrayの要素毎の処理

この先に使う処理方法をいくつか紹介する．

In [81]:
a = np.random.random(size=(5, 5))  # 処理対象の行列aを生成
print(a)

[[0.02588763 0.09420372 0.40684545 0.21277441 0.33498088]
 [0.65603081 0.97477828 0.32583387 0.54155292 0.00993695]
 [0.34215481 0.1058948  0.80600651 0.71386584 0.59992539]
 [0.56358663 0.41984403 0.42782346 0.04018598 0.89006028]
 [0.80788752 0.87102195 0.08011257 0.84068154 0.26831825]]


各要素へのアクセスは，行（高さ方向）の変数yと，列（横方向）の変数xの2重ループで行う．

In [82]:
h, w = a.shape  # 高さhと幅wを取得

for y in range(h):
    for x in range(w):
        a[y, x] += 1  # 各要素に1を足す

print(a)

[[1.02588763 1.09420372 1.40684545 1.21277441 1.33498088]
 [1.65603081 1.97477828 1.32583387 1.54155292 1.00993695]
 [1.34215481 1.1058948  1.80600651 1.71386584 1.59992539]
 [1.56358663 1.41984403 1.42782346 1.04018598 1.89006028]
 [1.80788752 1.87102195 1.08011257 1.84068154 1.26831825]]


In [83]:
b = np.zeros(a.shape)

for y in range(h):
    for x in range(w):
        if a[y, x] >= 1.5:
            b[y, x] = a[y, x]  # 1.5以上の要素をコピーする

print(b)

[[0.         0.         0.         0.         0.        ]
 [1.65603081 1.97477828 0.         1.54155292 0.        ]
 [0.         0.         1.80600651 1.71386584 1.59992539]
 [1.56358663 0.         0.         0.         1.89006028]
 [1.80788752 1.87102195 0.         1.84068154 0.        ]]


各要素で独立の処理は，pythonでは2重ループを使わず，行列に対する演算を使って次のように1行で書くこともできる（そしてかなり高速）

In [84]:
a = np.random.random(size=(5, 5))
print(a)

a += 1  # 各要素に1を足す
print(a)

b = a * 10  # 各要素を10倍する
print(b)

a[1, :] *= 100  # 行単位での演算も可能
print(a)

[[0.07365848 0.74975928 0.70997639 0.80473214 0.65758425]
 [0.06848193 0.8244799  0.91109924 0.86862298 0.60770681]
 [0.90846675 0.0449284  0.87676515 0.35135665 0.8815526 ]
 [0.60470956 0.34213761 0.3808195  0.21168503 0.08628658]
 [0.9141797  0.98881088 0.55495424 0.22669892 0.97945226]]
[[1.07365848 1.74975928 1.70997639 1.80473214 1.65758425]
 [1.06848193 1.8244799  1.91109924 1.86862298 1.60770681]
 [1.90846675 1.0449284  1.87676515 1.35135665 1.8815526 ]
 [1.60470956 1.34213761 1.3808195  1.21168503 1.08628658]
 [1.9141797  1.98881088 1.55495424 1.22669892 1.97945226]]
[[10.73658476 17.49759278 17.09976387 18.04732143 16.57584247]
 [10.68481934 18.244799   19.11099243 18.68622984 16.0770681 ]
 [19.0846675  10.44928398 18.76765154 13.51356647 18.81552595]
 [16.04709559 13.42137611 13.80819496 12.11685033 10.86286584]
 [19.141797   19.88810884 15.54954241 12.26698921 19.79452263]]
[[  1.07365848   1.74975928   1.70997639   1.80473214   1.65758425]
 [106.84819344 182.44799004 191.10

### Task

8x4の乱数行列aを生成してください．

そして，a全体に1を足してください．
この処理を，2重ループを使う方法と，行列に対する演算をつかって1行でかく方法の2通りを書いてください．


### 行列に対する等号不等号

arrayに対して等号・不等号も可能である（要素ごとに処理）．

これをつかって以下のtaskを行う．

In [85]:
a = np.random.randint(10, size=(3, 4))
print(a)
print(a == 1)

a = np.random.random(size=(5, 5))
print(a)
print(a > 1.5)

[[6 9 5 8]
 [7 5 4 6]
 [5 7 2 9]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[0.84107651 0.65085981 0.54392169 0.57666437 0.4197797 ]
 [0.21671811 0.19484587 0.65287058 0.07991988 0.66768289]
 [0.39757335 0.16181144 0.17937395 0.99466656 0.1099148 ]
 [0.87201739 0.45305668 0.32359882 0.25145071 0.29743469]
 [0.81809582 0.0996451  0.82463421 0.99475686 0.39742654]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


### Task

8x4の乱数行列aを生成してください．
そして，aの要素が0.5以上のものだけをゼロ行列bにコピーしてください．
これは上記の2重ループで行った処理と同じですが，2重ループを使わずに行ってください．

ヒント：

- 0.5以上かどうかのbool値行列を，別の変数に保存します
- bool値行列を，01の整数行列に変換します
- 元の行列aと整数行列の要素ごとの積を計算します

pythonではループ処理は非常に遅いです．できるだけループを使わない方法を考えましょう（ループを使わないほうが高速になります）．




## 便利な関数

リストやarrayに対する便利な関数を紹介します．

In [7]:
a = [6, 7, 2, 3, 0, 0, 3, 8, 3, 4]  # リスト
print(a)

print("max is ", max(a))  # 最大値
print("min is ", min(a))  # 最小値
print("sum is ", sum(a))  # 合計

[6, 7, 2, 3, 0, 0, 3, 8, 3, 4]
max is  8
min is  0
sum is  36


In [87]:
a = np.random.randint(10, size=(3, 3))  # 2D array
print(a)

print("mean is ", a.mean())  # 平均
print("standard deviation is ", a.std())  # 標準偏差
print("variance is ", a.var())  # 分散

print("max is ", a.max())
print("min is ", a.min())
print("sum is ", a.sum())
print("median is ", np.median(a))  # メディアン，中央値

[[6 5 5]
 [5 7 5]
 [8 6 3]]
mean is  5.555555555555555
standard deviation is  1.3425606637327303
variance is  1.8024691358024691
max is  8
min is  3
sum is  50
median is  5.0


In [46]:
a = np.random.randint(10, size=(3, 3))  # 2D array
print("this is a 2D array.")
print(a)

b = a.flatten()  # 2Dを1Dに変換する（flatten = フラットにする）
print("now it is a 1D array.")
print(b)

c = b.reshape(3, 3)  # 1Dを2Dに変形する
print("OK, let's make it to 2D again...")
print(c)

d = c.T  # 行列の転置
print("and transpose it.")
print(d)

d = c.transpose()  # 行列の転置はこれでもOK
print(d)

this is a 2D array.
[[2 4 7]
 [6 3 6]
 [5 3 6]]
now it is a 1D array.
[2 4 7 6 3 6 5 3 6]
OK, let's make it to 2D again...
[[2 4 7]
 [6 3 6]
 [5 3 6]]
and transpose it.
[[2 6 5]
 [4 3 3]
 [7 6 6]]
[[2 6 5]
 [4 3 3]
 [7 6 6]]


### Task

3x4の乱数行列を生成し，最大・最小・中央値・平均・標準偏差を求めてください．

次にそれをflatten()で1次元のarrayに変換したあと，今度はreshape()で6x2の行列に変形してください．

その6x2行列の最大値・最小値・中央値・平均・標準偏差を求めて，同じ値になることを確認してください.