# Pythonとnumpy簡易資料

- 講義では以降，線形代数で習ったような行列計算を頻繁に用いる．
  - 行列演算は一見，何の役に立つのかわからないかもしれないが多数の変量を統一的に整理するのにとても便利なので情報処理ではよく使われる（例えば画像は一つの行列とみなせる）．
  - ひたすら定義が続くので退屈かもしれないが，一連の演算は今後の基礎となる（また，研究でも線形代数演算を使うことは多い）
- この資料では，Pythonで行列計算を行う際に用いるモジュールnumpyについて紹介する．必要に応じてインターネットや書籍で適宜調べながら進めること．

  - NumPy Developers, [NumPy Reference](https://numpy.org/doc/stable/reference/index.html)
  - note.nkmk.me, [NumPy関連記事まとめ](https://note.nkmk.me/python-numpy-post-summary/)
  - Python学習講座, [Numpy入門](https://www.python.ambitious-engineer.com/numpy-index)
  - DXCEL WAVE, [Numpy基本操作一覧](https://di-acc2.com/programming/python/4896/)



講義資料にある**線形代数の演算を確認したのち** （特に例年，**行列とベクトルの掛け算の定義**を忘れている人が多いので，自信のない人は線形代数のテキストなども参考によく確認すること），以下のnumpyに関する説明を実際にを**動かして挙動を確認し**，課題に取り組むこと．

無味乾燥な計算の羅列に見えるかもしれないが，今後の課題でもここで行っているような演算が基本操作として頻出するため，行列計算の仕方をよく理解しておくこと．

明示的に使用を避けるよう記載されているものを除いてnumpyの機能を使って構わない．

なおPDF資料のように紙面上の数式では添字は1から始めることが多いが（$v_1, \ldots, v_n$など），プログラムの添字は0から始まる（`v[0], ..., v[n-1]`など）ので注意すること．

## ベクトル

example01では長さ5のベクトルであるnp.ndarrayクラスのインスタンス`x`を`np.array()`で生成している．引数には実数値のリストを与えると，実数のndarrayが生成される（以降は実数を扱うが，整数のndarrayも利用可能）．

np.arrayは`print()`に直接渡すことができ，ベクトル内の全要素を表示させることができる．




In [1]:
# example01

import numpy as np

x = np.array([1., 2., 3., 4., 5.])  # 「1」は整数なので，「1.」のようにして実数にする

print("x = ")
print(x)

print("x = ", x)

x = 
[1. 2. 3. 4. 5.]
x =  [1. 2. 3. 4. 5.]


numpyを利用するためには`import numpy as np`を実行する必要がある．これは各セルでの実行は必要なく，カーネルが起動してから1回だけ実行しておけばよい．

In [2]:
import numpy as np

このクラスでは，`np.zeros(n)`で長さ$n$のゼロベクトルが定義できる．定義された変数`x`の`i`番目の要素にアクセスするには`x[i]`とする（添字は0から始まる）．example02では，0番目の要素から順番に値を代入している．


In [3]:
# example02

# example01と同じことを行う

x = np.zeros(5)  # ndarray（次元数: 5）

# 各要素への値の代入
x[0] = 1.
x[1] = 2.
x[2] = 3.
x[3] = 4.
x[4] = 5.

print("x = ", x)

x =  [1. 2. 3. 4. 5.]


他にベクトルを生成するには以下のような方法がある．それぞれ作成して表示し，確認すること．

In [4]:
x = np.zeros(5)  # 全て0のベクトル

# 各自で表示すること．以下同様

In [5]:
y = np.zeros_like(x)  # xと同じ形状の，全て0のベクトル


In [6]:
x = np.ones(5) # 全て1のベクトル

In [7]:
x = np.random.rand(5)  # 正規乱数のベクトル

In [8]:
# 0から90まで（90を含まない）の10.0刻みの値を要素にもつベクトル（等差数列）
x = np.arange(0, 90, 10.0)

In [9]:
# 0から90までの値を10等分した数列
x = np.linspace(0, 90, 10)

以下のようにすると実数と整数のndarrayを変換できる．

In [10]:
x = np.zeros(5)  # 全て0のベクトル．デフォルトで実数
print(x, x.dtype)

x = x.astype(int)  # 整数への変換
print(x, x.dtype)

x = x.astype(float)  # 実数への変換
print(x, x.dtype)

[0. 0. 0. 0. 0.] float64
[0 0 0 0 0] int64
[0. 0. 0. 0. 0.] float64


作成時に整数と実数の型を指定できる．
数値計算では実数型を使うため，作成時に整数にならないように気をつけること．

In [11]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])  # 整数のndarray
print(x, x.dtype)

x = x.astype(float)
print(x, x.dtype)

x = np.array([1, 2, 3, 4, 5]).astype(float)  # astypeで実数型に変換
print(x, x.dtype)

x = np.array([1, 2, 3, 4, 5], dtype=float)  # 作成時にdtypeを指定して実数にする
print(x, x.dtype)

x = np.array([1., 2., 3., 4., 5.])  # 実数のndarray
print(x, x.dtype)

x = np.array([1., 2., 3., 4., 5.], dtype=int)  # 作成時にdtypeを指定して整数にする
print(x, x.dtype)


[1 2 3 4 5] int64
[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.] float64
[1 2 3 4 5] int64


## 行列

ndarrayは行列も表現できる．

下の例では，$3 \times 2$の行列`M`を宣言し，各要素に値を代入し，表示させている．
ベクトルのとき同様，任意の$i, j$要素に`M[i, j]`というフォーマットでアクセスできる．

また，その後，単位行列を`np.eyes()`で生成する例を示している．


In [12]:
# example03

# 行列クラス（3 x 2で作成）
M = np.zeros((3, 2))  # タプル(3, 2)をnp.zeros()の引数に与えている

# 各要素に代入
M[0, 0] = 1.
M[0, 1] = 2.
M[1, 0] = 3.
M[1, 1] = 4.
M[2, 0] = 5.
M[2, 1] = 6.

print("M:")
print(M)

# 以下のようにすると3x3の単位行列が作られる
I = np.eye(3)

print("I:")
print(I)

M:
[[1. 2.]
 [3. 4.]
 [5. 6.]]
I:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


`np.array()`で行列生成するには，二重リスト`[ [], ..., [] ]`を与える．

以下の例では，3行2列の行列を生成しているが，二重リストの引数の順番は1行目，2行目，3行目であり，各行で1列目，2列目，3列目の値を指定する．

In [13]:
# example04

M = np.array([[1., 2.],
              [3., 4.],
              [5., 6.]])

print("M:")
print(M)

M:
[[1. 2.]
 [3. 4.]
 [5. 6.]]


行列も整数と実数の型を使い分けられる．
数値計算では実数型を使うため，作成時に整数にならないように気をつけること．

In [14]:

M = np.array([[1., 2.],
              [3., 4.],
              [5., 6.]])
print(M, M.dtype)

M = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(M, M.dtype)  # これでは整数型になってしまう

M = np.array([[1, 2],
              [3, 4],
              [5, 6]], dtype=float)
print(M, M.dtype)

M = np.array([[1, 2],
              [3, 4],
              [5, 6]]).astype(float)
print(M, M.dtype)



[[1. 2.]
 [3. 4.]
 [5. 6.]] float64
[[1 2]
 [3 4]
 [5 6]] int64
[[1. 2.]
 [3. 4.]
 [5. 6.]] float64
[[1. 2.]
 [3. 4.]
 [5. 6.]] float64


## 情報へのアクセス

行列やベクトルのサイズの取得．行列の行数や列数，ベクトルの次元を確認する方法は以下の通り

In [15]:
# example05

M = np.array([[1., 2.],
              [3., 4.],
              [5., 6.]])
v = np.zeros(10)

print("M")
print("shape: ", M.shape)
print("rows: ", M.shape[0])  # 行数
print("cols: ", M.shape[1])  # 列数

print("v")
print(len(v))  # ベクトルの次元
print(v.shape)
print(v.shape[0])

M
shape:  (3, 2)
rows:  3
cols:  2
v
10
(10,)
10


以下のようにすると行列の行や列の抽出ができる

In [16]:
# example06

M = np.array([[1., 2.],
              [3., 4.],
              [5., 6.]])

# 行の取得
print("1st row", M[0])
print("2nd row", M[1])
print("3rd row", M[1])

# 行の取得その２．上記は以下の省略形
print("1st row", M[0, :])  # 「：」はその次元のすべての要素を意味する
print("2nd row", M[1, :])
print("3rd row", M[1, :])

# 列の取得
print("1st column", M[:, 0])
print("2nd column", M[:, 1])

1st row [1. 2.]
2nd row [3. 4.]
3rd row [3. 4.]
1st row [1. 2.]
2nd row [3. 4.]
3rd row [3. 4.]
1st column [1. 3. 5.]
2nd column [2. 4. 6.]


## 線形代数演算

np.ndarrayには演算子が定義されており，行列の演算を直感的に書くことができる．



### 和

ベクトルや行列の和は演算子`+`を適用するだけで，実行できる．

In [17]:
# example07


# ベクトルの和

v = np.ones(5)
u = np.arange(1, 6, 1)

print("v = ", v)
print("u = ", u)
  
v_plus_u = v + u

print("v + u = ", v_plus_u)
print("v + u = ", v + u)



# 行列の和　

M = np.random.rand(2, 3)
N = np.random.rand(2, 3)

print("M = ", M)
print("N = ", N)
  
M_plus_N = M + N

print("M + N = ", M_plus_N)
print("M + N = ", M + N)


v =  [1. 1. 1. 1. 1.]
u =  [1 2 3 4 5]
v + u =  [2. 3. 4. 5. 6.]
v + u =  [2. 3. 4. 5. 6.]
M =  [[0.92276852 0.87415557 0.30932131]
 [0.39094804 0.26486138 0.04128399]]
N =  [[0.85048173 0.58621924 0.49646173]
 [0.59078465 0.62159969 0.84713679]]
M + N =  [[1.77325025 1.46037481 0.80578304]
 [0.98173269 0.88646106 0.88842077]]
M + N =  [[1.77325025 1.46037481 0.80578304]
 [0.98173269 0.88646106 0.88842077]]


### 行列積

行列とベクトルの積の計算には，以下のように

- 演算子`@`を用いる方法
- メソッド`dot()`を用いる方法
- 関数`np.dot()`を用いる方法

がある．演算子`@`がもっとも直感的で，数式との相性もよい．


注意：演算子`*`は要素ごとの積であり，行列積ではない．

In [18]:
# example08

M = np.array([[1., 2.],
              [3., 4.],
              [5., 6.]])
v = np.array([1, 1])

u = M @ v
print(u)

# 以下の3つは同じ計算をする
print(M @ v)
print(np.dot(M, v))
print(M.dot(v))

[ 3.  7. 11.]
[ 3.  7. 11.]
[ 3.  7. 11.]
[ 3.  7. 11.]


### 転置

行列やベクトルの転置は`.T`で行う．

この例では，$3 \times 2$行列$\mathbf{M}$と次元$3$のベクトル$\mathbf{v}$の転置$\mathbf{M}^\top$, $\mathbf{v}^\top$を表示している．
さらに，$\mathbf{M}^\top \mathbf{v}$を計算した結果を表示している
（行列の掛け算の定義より，サイズが合わないため$\mathbf{M} \mathbf{v}$は定義されないことに注意）．

In [19]:
# example09

M = np.array([[1., 2.],
              [3., 4.],
              [5., 6.]])
v = np.array([1, 2, 3])

print("M\n", M)
print("v\n", v)


print("M^T =\n", M.T)
print("v^T =\n", v.T)


print("M^T v =")
# 以下の3つは同じ計算をする
print(M.T @ v)
print(M.T.dot(v))
print(np.dot(M.T, v))


M
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
v
 [1 2 3]
M^T =
 [[1. 3. 5.]
 [2. 4. 6.]]
v^T =
 [1 2 3]
M^T v =
[22. 28.]
[22. 28.]
[22. 28.]


### 内積

ベクトル$\mathbf{v}$と$\mathbf{u}$の内積($\mathbf{v}^\top \mathbf{u}$)は，以下のように

- 演算子`@`を用いる方法
- メソッド`dot()`を用いる方法
- 関数`np.dot()`を用いる方法

がある．演算子`@`がもっとも直感的で，数式との相性もよい．


In [20]:
# example10

v = np.array([1, 1])
u = np.array([2, -1])
M = np.ones((2, 2))  # 要素が全て1の2x2行列

print("v", v)
print("u", u)
print("M", M)

#
# 内積計算 例1: v^T u
#
print("v^T u:")

# 以下の4つは同じ計算をする
print(v @ u)
print(v.T @ u)
print(v.dot(u))
print(np.dot(v, u))


#
# 内積計算 例2: v^T M u
#
print("v^T M u:")

# 以下の3つは同じ計算をする
print(v.T @ M @ u)
print(v.dot(M.dot(u)))
print(np.dot(v, np.dot(M, u)))


v [1 1]
u [ 2 -1]
M [[1. 1.]
 [1. 1.]]
v^T u:
1
1
1
1
v^T M u:
2.0
2.0
2.0


### 逆行列計算

逆行列の計算には`np.linalg.inv()`を使う．

In [21]:
# example11

M = np.array([[3., 1., 2.],
              [0., 2., 1.],
              [1., 1., 3.]])
print("M = ")
print(M)

Minv = np.linalg.inv(M)
print("M^{-1} = ")
print(Minv)


M = 
[[3. 1. 2.]
 [0. 2. 1.]
 [1. 1. 3.]]
M^{-1} = 
[[ 0.41666667 -0.08333333 -0.25      ]
 [ 0.08333333  0.58333333 -0.25      ]
 [-0.16666667 -0.16666667  0.5       ]]


### その他


In [22]:
# 円周率π
print(np.pi)

3.141592653589793


In [23]:
# sin, cos
print(np.sin(0.0))
print(np.cos(np.pi / 2.))

0.0
6.123233995736766e-17


In [24]:
# 平方根
print(np.sqrt(2))

1.4142135623730951
